### ISSUE TITLE
loosened node cohesion x2

### ISSUE THREAD

**Issue by jcamp0424** [phg49389/drg-weapons-calculator#37]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
there is 2 loosened node cohesion in the breach cutter skill tree.

**Comment by jcamp0424** [comment]
there is also mislabled things. such as the max ammo for the breach cutter. please update all of the stats for the program please and thank you.

**Comment by phg49389** [comment]
Thanks for submitting the bug report! Which version of the DPS Calculator are you using? As of DRG Update 32, Breach Cutter only has one Loosened Node Cohesion mod at T2.C, and I updated the DPSC to mirror that change in [v1.0.6](https://github.com/drg-tools/drg-weapons-calculator/releases/tag/v1.0.6) along with all of the other balance changes that took place that update.

I'm currently working on v1.0.7 to release next week after Update 33 stops having hotfixes applied, and if any weapon balance changes happen in a hotfix I'll make sure that they get implemented before I release v1.0.7 to the public. There will be several bugfixes as well as implementations of Revolver's T5.A Dead-Eye, Cryo Cannon's T5.A Fragile, and Flamethrower's T5.B Targets Explode.

**Comment by jcamp0424** [comment]
Windows, would you like a picture of what I see?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jcamp0424** [comment]
[Image.jpeg]There’s 2 loosed node cohesions
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jcamp0424** [comment]
I have 1 at T2.C and T3.B

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by phg49389** [comment]
If you run the program and look at the top-left of its GUI, there should be some text that says "MeatShield's DRG DPS Calculator (DRG Update __)"

What DRG Update does it say that it was compiled for? It sounds like you're using v1.0.5, which was compiled for DRG Update 31.5

**Comment by jcamp0424** [comment]
It says 31.5, how do I update to a newer version?


________________________________

**Comment by jcamp0424** [comment]
Never mind I have found it, sorry about that


________________________________

**Comment by phg49389** [comment]
No worries! Glad I was able to help you. Like I mentioned in an earlier comment, v1.0.6 is up-to-date with Update 32 and I'm working on finishing v1.0.7 to release next week after Update 33 finishes getting its hotfixes in case GSG sneaks in any weapon balance updates. 

Because the "bug" has been resolved, I'm going to close this issue.
