### ISSUE TITLE
Adding the Glyphid Menace in the Breakpoint window

### ISSUE THREAD

**Issue by Sad-theFaceless** [phg49389/drg-weapons-calculator#40]
Hello, that's simple, I use the breakpoint calculations a lot especially to help to mod my M1000, but I noticed a certain HPT isn't displayed.

I was thinking that would be nice to add the Glyphid Menace in there as well, I think it makes sense especially for the M1000.

Thanks !

**Comment by phg49389** [comment]
Added Menaces to Breakpoint window. This will be available in the next release, 1.0.8, which I just started the process of packaging. It should be pushed out within an hour if all goes well.

Feature added; closing issue.
