### ISSUE TITLE
When Time to Empty Mag < 1 sec it shouldn't calc like burst size is big enough to be able to shoot during this whole second

### ISSUE THREAD

**Issue by converal** [phg49389/drg-weapons-calculator#48]
Boomstick now suddenly having 2.4k burst dps lmao

**Comment by phg49389** [comment]
I'm not sure that's actually a bug. You're right; Boomstick can't do 2,400 damage in one second. But on the other hand, that's not what the DPS metric is actually measuring. DPS is just that: "what is the rate of damage dealt in relation to the number of seconds required".

**Comment by converal** [comment]
Anyways - it's not good for practical comparison. If it doesn't match definition of DpS as you say - name it other way, that's not the issue. If I want to compare Burst DpS of NUK17 with 2 thousands of Boomstick - well, boomstick always wins that way :D For boomstick DpS doesn't really matter, it's damage per shot and damage per magazine what matters and it's actually not shown anywhere there. I have to either use brain, calculator or karl.gg:
![image](https://user-images.githubusercontent.com/16324267/141432570-e4456c49-4859-401f-a57c-edbb0c3d3d3d.png)
It's actually surprising that 3 out of 4 calclulated stats of Karl.gg are not shown in this software. Are they supposed to work together? I can't rely on total multi-target damage stat, in most of cases I'm not able to realise its potential. And when I pick some blowthrough mod suddenly another single target weapon becomes uncomparable to this weapon in terms of total damage. Again, I talk about practical comparison. I know in theory it all makes sense, but I believe it's not phantasy project. Moreover, there's like one and only DpS build based on Double Barrel OC and it uses Sustained DpS to prove its worth, not Burst DpS. So Burst DpS right now is useless to me as a user of boomstick. Thus, I suggest at least implementing magazine damage instead of burst dps for boomstick (way more sense to me) and splitting total multi-target damage to total damage like in Karl.gg and multi-target total potential damage as it was a problem for other weapons too.

**Comment by phg49389** [comment]
Damage per Magazine is actually already calculated by the DPS Calculator, but it's not one of the metrics displayed in the bottom panel. It can be found on Karl.gg in the ["Advanced Statistics View"](https://karl.gg/asv/7/AACAC3), or you can use the Export to CSV functionality to get it as one of the columns for the weapon.

Damage per Shot isn't a metric that I'm interested in modeling in my program. It's not really useful for players' in-game performance optimization, and it's indirectly accounted for in the Max Multi-Target Damage metric. At the end of the day, that metric is just Damage per Shot times Ammo plus DoTs.

One of the features I want to get done for the full U35 release is something requested by Milligin; a breakdown of Max Damage by number of targets hit. It would work similarly to Breakpoints and Overkill, a pop-up panel that would say how much damage is dealt to [1 enemy, 2, 3, 4, 5, 10, 15, ... Max Num Targets] or something like that. That should more than account for the third metric you asked for.

As for the last point -- DPS Calculator is designed to provide theoretical numbers in every circumstance. Practical comparisons really break down when compared against theory like the stuff this program does. I don't want to try to contort this program into a "practical comparisons"-shaped form it doesn't fit into; this is a tool designed to provide knowledge and theoretical numbers in best-case scenarios.
