### ISSUE TITLE
Tooltip for calculation formula when hovering cursor over stat name

### ISSUE THREAD

**Issue by converal** [phg49389/drg-weapons-calculator#51]
I think sometimes it becomes interesting how programm calculated that. Would be way better and more on point than wall of text in info section

**Comment by phg49389** [comment]
I'm not going to implement this suggested feature. What you're asking is for the source code of every method to be a tooltip, and this program is like 20,000 lines of code. Some of those tooltips would be larger than some people's monitors.

If you're really keen to see how the calculations work behind the scene, this is an open-source code repository. Feel free to go to the relevant weapon files and see the source code directly 😃
