### ISSUE TITLE
EXPORT CSV DOESNT WORK FOR DRAK

### ISSUE THREAD

**Issue by converal** [phg49389/drg-weapons-calculator#54]
![image](https://user-images.githubusercontent.com/16324267/141681650-0225b7f3-f0bd-4551-8773-fef177927893.png)

**Comment by phg49389** [comment]
Unable to replicate on my computer. How long did you give it to run? It takes 2-10 seconds depending on the weapon.

**Comment by converal** [comment]
I didn't choose any mods nor OCs. You just go to DRAK's tab and press Export current weapon's metrics to CSV button. 3-Click replication.

**Comment by phg49389** [comment]
When I run it on my computer, this is the output file that I get.

[Scout_PlasmaCarbine.csv](https://github.com/drg-tools/drg-weapons-calculator/files/7548040/Scout_PlasmaCarbine.csv)

**Comment by converal** [comment]
It's fine now, I think I was closing it too early. I only now noticed that busy cursor after this operation. Though for hurricane it was not the case lol
